CREATE TABLE `customer` (
  `CustomerId` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(255) NOT NULL,
  `LastName` VARCHAR(255) NOT NULL,
  `Phone` VARCHAR(25) DEFAULT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Street` VARCHAR(255) DEFAULT NULL,
  `City` VARCHAR(50) DEFAULT NULL,
  `State` VARCHAR(25) DEFAULT NULL,
  `Zip` VARCHAR(5) DEFAULT NULL,
  PRIMARY KEY (CustomerId)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;