CREATE TABLE `store` (
  `StoreId` INT NOT NULL AUTO_INCREMENT,
  `StoreName` VARCHAR(255) NOT NULL,
  `Phone` VARCHAR(25) DEFAULT NULL,
  `Email` VARCHAR(255) DEFAULT NULL,
  `Street` VARCHAR(255) DEFAULT NULL,
  `City` VARCHAR(255) DEFAULT NULL,
  `State` VARCHAR(10) DEFAULT NULL,
  `Zip` VARCHAR(5) DEFAULT NULL,
  PRIMARY KEY (StoreId)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;